[server]
maxUploadSize = 1

# theme: nord-dark
[theme]
base = 'dark'
primaryColor = '#88C0D0'
backgroundColor = '#2E3440'
secondaryBackgroundColor = '#3B4252'
textColor = '#E5E9F0'

font = 'monospace'